### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by yzgan** [pizzasaurusrex/TestObject#2]
I was able to update TestObject test with following
```js
const TestObject = require('testobject_api');
const testObjectService = new TestObject({
  username: process.env.SAUCE_USERNAME,
  apiKey: process.env.TESTOBJECT_API_KEY_ANDROID,
  password: ''
});
testObjectService.updateTest(browser.sessionId, {"passed": false});
```
but in server log, it showed error in the following: 
```
/Users/*/node_modules/testobject_api/lib/TestObject.js:250
    callback(err, res, body);
    ^

TypeError: callback is not a function
    at Request._callback (/Users/*/node_modules/testobject_api/lib/TestObject.js:250:5)
    at Request.self.callback (/Users/*/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/*/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/*/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```
`package.json` with
```
"testobject_api": "^2.0.0",
```

It seemed like the issue caused by `callback` function not recognized in the library. Was it a bug?

**Comment by pizzasaurusrex** [comment]
Yes this looks like a bug. callback should have a default value if is is not defined in the method call.

**Comment by pizzasaurusrex** [comment]
[fixed](https://github.com/pizzasaurusrex/TestObject/pull/3)

some of the other methods might cause issues.
I'll try to fix them over the weekend, and this project needs some TLC - feel free to open another issue or submit a pr : )

**Comment by yzgan** [comment]
that was a quick fix! 👍
